# promptfooconfig.yaml
description: "File-based prompt demo"
providers:
  # - id: openai:gpt-5
  #   config: 
  #   verbosity: high # low | medium | high
  #   reasoning_effort: minimal                               # OpenAI model ID
  # - id: anthropic:messages:claude-sonnet-4-20250514   # Claude Sonnet model ID
  # - id: openai:local  # Local model served by LM Studio
  #   config:
  #     apiBaseUrl: http://localhost:1234/v1          # Local API base URL
  #     apiKey: lmstudio                              # API key for local model
  #     model: openai/gpt-oss-20b               # Model identifier
  #     temperature: 0.7
  #     max_tokens: 300
  - file://prompts/providers.yml  # Load providers from external YAML file
prompts:
  # Each entry pulls a template from an external text file in ./prompts
  - file://prompts/customer_service.txt
  - file://prompts/technical_support.txt

tests:
  -file://prompts/tests.yaml  # Load tests from external YAML file
    