# promptfooconfig.yaml
description: "Multiline prompt demo"
providers:
  - openai:gpt-4o                                 # OpenAI model ID
  - anthropic:messages:claude-sonnet-4-20250514   # Claude Sonnet model ID
  - id: openai:local  # Local model served by LM Studio
    config:
      apiBaseUrl: http://localhost:1234/v1          # Local API base URL
      apiKey: lmstudio                              # API key for local model
      model: openai/gpt-oss-20b               # Model identifier
      temperature: 0.7
      max_tokens: 300

prompts:
  - |-
    You are a helpful assistant.

    Please answer the following question:
    {{question}}

    Provide a detailed explanation.

tests:
  - vars:
      question: "Why is the sky blue?"

  - vars:
      question: "What is the capital of France?"

  - vars:
      question: "Explain the theory of relativity in simple terms."